/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'Create Pet': ApiRouteHandler<{ name: string; breed: string; age: number }, ApiResponse<200, { id: string; name: string; breed: string; age: number }>, never>
    'Get Pets': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { pets: { id: string; name: string; breed: string; age: number }[] }>, never>
  }
}